[font]
size = 9.0
normal = { family = "Fira Mono" } 

[general]
import = [
    "themes/gruvbox_material_hard_dark.toml"
]

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 500
blink_timeout = 0
