[font]
size = 10.0
normal = { family = "Fira Mono" } 

[general]
import = [
    "themes/one_dark.toml"
]

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 500
blink_timeout = 0
